import { build } from "esbuild";
import { readFile } from "node:fs/promises";
const license = await readFile("node_modules/ws/LICENSE", "utf8");
await build({
  entryPoints: ["scripts/botspace-client.mjs"],
  outfile: "plugins/botspace/scripts/client.mjs",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  external: ["bufferutil", "utf-8-validate"],
  banner: {
    js:
      "// Generated by npm run build:client. Edit scripts/botspace-client.mjs.\n/* Bundled ws license:\n" +
      license +
      '*/\nimport { createRequire } from "node:module"; const require = createRequire(import.meta.url);',
  },
});
